name: Test deployment
on: 
  workflow_dispatch

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: pull container
      run: docker pull arnoutcoenegrachtspxl/app:latest

    - name: stop any running containers
      run: |
        if [ $(docker ps -q \| wc -l) -gt 0];
          then
            echo "deleting active containers"
            docker rm -f -v $(docker ps -aq)
          else
            echo "no containers to delete"
        fi
    - name: run container
      run: docker run -p 8000:3000 -d arnoutcoenegrachtspxl/app:latest