name: Test deployment
on: 
  workflow_dispatch

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: pull container
      run: docker image pull arnoutcoenegrachtspxl/pxl-app:latest
    
    - name: stop any running containers
      run: docker rm -f -v $(docker ps -aq)

    - name: run container
      run: docker run -p 3000:3000 arnoutcoenegrachtspxl/pxl-app